---
title: "AirlineProject"
author: "Jake Lee"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## References and Datasets

**Airlines Delay** - By Ulrik Thyge Pedersen (Kaggle)

<https://www.kaggle.com/datasets/ulrikthygepedersen/airlines-delay>

**Airlines Customer Satisfaction** - By Sayantan Jana (Kaggle)

<https://www.kaggle.com/datasets/sjleshrac/airlines-customer-satisfaction/data>

**Airlines Traffic Passenger Statistics** - By The Devastator (Kaggle)

<https://www.kaggle.com/datasets/thedevastator/airlines-traffic-passenger-statistics>

## Reading Packages and Datasets

```{r}
#load required packages
library(ggplot2)
library(dplyr)
library(tidyverse)
library(plotly)
library(ggiraph)

passenger_stats <- read_csv("Datasets/Air_Traffic_Passenger_Statistics.csv")
delay <- read_csv("Datasets/airlines_delay.csv")
satis <- read_csv("Datasets/invistico_Airline.csv")
```

```{r}
#show summary of each datasets
summary(passenger_stats)
summary(delay)
summary(satis)
```

## Data Cleaning Process

### Passenger Statistics

```{r}
#check for NA values
any(is.na(passenger_stats))
any(is.na(satis))
```

```{r}
#select only international flights
passenger_stats <- passenger_stats %>%
  filter(`GEO Summary` == "International") %>%
  select(-c(`Passenger Count`, `Terminal`, `Boarding Area`)) %>%
  filter(`Operating Airline` == `Published Airline`) %>%
  select(-c(`Published Airline`, `Published Airline IATA Code`, `Price Category Code`, `index`, `GEO Summary`))
```

```{r}
summary(passenger_stats)
```

### Delay Statistics

```{r}
any(is.na(delay))
```

```{r}
delay <- delay %>%
  select(-`Class`)
```

```{r}
summary(delay)
```

### Satisfaction Score

```{r}
any(is.na(satis))
```

## Exploratory Data Analysis (EDA)

```{r}
# Which region has the most number of passengers who got deplaned
p_deplane_region <- passenger_stats %>%
  filter(`Activity Type Code`=='Deplaned') %>%
  ggplot(aes(Year, `Adjusted Passenger Count`, color = `GEO Region`)) +
  geom_point() +
  theme_bw()

ggplotly(p_deplane_region)
```

```{r}
# Which airline has the most number of passengers who got deplaned
p_deplane_airline <- passenger_stats %>%
  filter(`Activity Type Code`=='Deplaned') %>%
  ggplot(aes(Year, `Adjusted Passenger Count`, color = `Operating Airline IATA Code`)) +
  geom_point() +
  theme_bw()

ggplotly(p_deplane_airline)
```

```{r}
passenger_stats$Month <- match(passenger_stats$Month, month.name)

p_yearly_trend <-
  ggplot(passenger_stats, mapping = aes(
    x = Month,
    y = `Adjusted Passenger Count`
  )) + 
  geom_point() +
  geom_smooth(method = "lm", fit = `Adjusted Passenger Count` ~ Month) + 
  facet_wrap(~Year, scales = 'free_y')

p_yearly_trend
```

```{r}
# Create new df to calculate total passenger count in certain years
passenger_summary <- passenger_stats %>%
  group_by(Year, Month) %>%
  summarize(`Total Passenger Count` = sum(`Adjusted Passenger Count`))
```
